### ISSUE TITLE
Cannot resolve symbol 'MavenDeployment'

### ISSUE THREAD

**Issue by bimromatic** [AndroidAppFactory/AndroidAppFactory#3]

**Comment by bimromatic** [comment]
gradle 换成7.0+ 这个就出问题了

**Comment by bihe0832** [comment]
你好，应该是高版本的 AGP 弃用了MavenDeployment，你阔以网上搜索相关的解决方案，AAF由于涉及到Android Support 库切换到AndroidX，所以没有那么快适配最新的 AGP

**Comment by bimromatic** [comment]
好哒，谢谢

**Comment by bihe0832** [comment]
AAF  已经切换到了AndroidX，并适配到最新的AGP，一直忘了这里同步
