### ISSUE TITLE
无法运行，提示android.useAndroidX` property is not enabled，但是没有gradle.properties文件，无法设置android.useAndroidX

### ISSUE THREAD

**Issue by apkcoder** [AndroidAppFactory/AndroidAppFactory#5]
Caused by: com.android.builder.errors.EvalIssueException: Configuration `debugRuntimeClasspath` contains AndroidX dependencies, but the `android.useAndroidX` property is not enabled, which may cause runtime issues.

运行demo或者新建项目的模版代码，都提示没有打开AndroidX，设置这个又需要在gradle.properties文件，但是在这个项目中没有发现这个文件

**Comment by apkcoder** [comment]
> Caused by: com.android.builder.errors.EvalIssueException: Configuration `debugRuntimeClasspath` contains AndroidX dependencies, but the `android.useAndroidX` property is not enabled, which may cause runtime issues.
> 
> 运行demo或者新建项目的模版代码，都提示没有打开AndroidX，设置这个又需要在gradle.properties文件，但是在这个项目中没有发现这个文件

已解决，自己新建gradle.properties添加相关代码即可，不过还是不明白为啥这个项目中要把gradle.properties文件删除

**Comment by bihe0832** [comment]
一般 gradle.properties 文件都会包含 一些编译环境（例如编译路径等）、自定义数据（敏感数据）等，当多人开发中不同开发者设置不同容易有冲突，所以开发中一般都是使用全局配置，而不放在项目代码中。全局配置可以在 Android Studio 的 Settings 里面的 Gradle  配置设置。

后续我也会继续优化完善一下，在运行流程中增加对应的提示：https://android.bihe0832.com/doc/sample/start.html
